Repository nextyio/gonex, pull requests merged in 2019-03, with the labels that each got.

#162 params: enable ThangLong hardfork for testnet
  params/config.go
Labels: PR: unreviewed, testnet

#164 Correct the NTF manager to hardcoded address
  cmd/puppeth/wizard_genesis.go
  consensus/dccs/dccs.go
Labels: PR: reviewed-approved, testnet

#160 cmd/puppeth: integrate blockscout
  cmd/puppeth/module_explorer.go
  cmd/puppeth/wizard_explorer.go
  cmd/puppeth/wizard_network.go
Labels: PR: unreviewed, need:more-tests, priority:medium, status:in-progress

#161 Resolve deadlock due to low sync and offline signer
  core/blockchain.go
  core/headerchain.go
  eth/fetcher/fetcher.go
  eth/handler.go
  eth/sync.go
Labels: PR: reviewed-approved

#166 params: enable ThangLong hardfork on mainnet
  params/config.go
Labels: PR: reviewed-approved, mainnet, must:have

#167 dccs: NTF stake require should include 18 decimals
  consensus/dccs/dccs.go
Labels: PR: reviewed-approved, bug :beetle:

#170 core: pre-calculate transaction senders before locking txpool
  core/tx_pool.go
Labels: PR: unreviewed

#172 cmd/geth: revert the client identifier to geth
  cmd/geth/main.go
Labels: PR: unreviewed

#174 cmd: rename command geth to gonex
  Makefile
  cmd/gonex/accountcmd.go
  cmd/gonex/accountcmd_test.go
  cmd/gonex/bugcmd.go
  cmd/gonex/chaincmd.go
  cmd/gonex/config.go
  cmd/gonex/consolecmd.go
  cmd/gonex/consolecmd_test.go
  cmd/gonex/dao_test.go
  cmd/gonex/genesis_test.go
  cmd/gonex/main.go
  cmd/gonex/misccmd.go
  cmd/gonex/monitorcmd.go
  cmd/gonex/run_test.go
  cmd/gonex/testdata/empty.js
  cmd/gonex/testdata/guswallet.json
  cmd/gonex/testdata/passwords.txt
  cmd/gonex/testdata/wrong-passwords.txt
  cmd/gonex/usage.go
Labels: PR: unreviewed
