Repository nextyio/gonex, pull requests merged in 2019-07, with the labels that each got.

#241 dccs: looping until data/state are available on local
  consensus/dccs/dccs.go
  consensus/dccs/snapshot.go
Labels: PR: reviewed-approved

#233 vendor: udpate leveldb upstream
  vendor/github.com/syndtr/goleveldb/leveldb/db.go
  vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go
  vendor/github.com/syndtr/goleveldb/leveldb/db_snapshot.go
  vendor/github.com/syndtr/goleveldb/leveldb/db_transaction.go
  vendor/github.com/syndtr/goleveldb/leveldb/session.go
  vendor/github.com/syndtr/goleveldb/leveldb/session_compaction.go
  vendor/github.com/syndtr/goleveldb/leveldb/session_util.go
  vendor/github.com/syndtr/goleveldb/leveldb/table.go
  vendor/github.com/syndtr/goleveldb/leveldb/version.go
  vendor/vendor.json
Labels: PR: unreviewed, enhancement :up:, upstream

#243 dccs: re-apply dccs consensus to master branch
  consensus/dccs/api.go
  consensus/dccs/dccs.go
  consensus/dccs/snapshot.go
Labels: PR: reviewed-approved

#244 cmd,eth: reword message log to Nexty
  cmd/gonex/main.go
  eth/handler.go
Labels: PR: reviewed-approved

#245 dccs: cast vote if the block is not a checkpoint
  consensus/dccs/dccs.go
Labels: PR: reviewed-approved, bug :beetle:

#248 Modify Dockerfile for gonex
  Dockerfile
  Dockerfile.alltools
Labels: PR: reviewed-approved

#250 accounts,ethclient,internal,mobile: add eth api to get mru number
  internal/ethapi/api.go
  internal/jsre/deps/bindata.go
  internal/jsre/deps/web3.js
  mobile/ethclient.go
Labels: PR: reviewed-approved

#251 accounts,ethclient,internal,mobile: add eth api to get mru number (#250)
  internal/ethapi/api.go
  internal/jsre/deps/bindata.go
  internal/jsre/deps/web3.js
  mobile/ethclient.go
Labels: PR: reviewed-approved

#254 params: update trusted checkpoint
  params/config.go
Labels: PR: reviewed-approved

#252 internal: add web3 extension for dccs
  internal/web3ext/web3ext.go
Labels: PR: reviewed-approved

#253 internal: add web3 extension for dccs
  internal/web3ext/web3ext.go
Labels: PR: reviewed-approved

#256 Implement real backend
  accounts/abi/bind/backends/real.go
  core/evm.go
  core/state_transition.go
  params/config.go
Labels: PR: unreviewed
