Repository nextyio/gonex, pull requests merged in 2019-06, with the labels that each got.

#212 update trusted checkpoint for testnet also
  params/config.go
Labels: PR: reviewed-approved, testnet

#213 backport re-naming into 2.0.1 release
  .gitignore
  cmd/gonex/config.go
  cmd/gonex/consolecmd.go
  cmd/gonex/main.go
  cmd/gonex/monitorcmd.go
  console/console.go
  eth/backend.go
  node/config.go
  node/defaults.go
  params/version.go
Labels: PR: reviewed-approved

#217 params: add official testnet nodes as default bootnodes
  params/bootnodes.go
Labels: PR: reviewed-approved, testnet

#197 NeUSD and supply absoption
  .gitignore
  accounts/abi/bind/backends/real.go
  cmd/puppeth/wizard_genesis.go
  common/big.go
  common/deployer/contract.go
  consensus/clique/clique.go
  consensus/consensus.go
  consensus/dccs/dccs.go
  consensus/dccs/feeder.go
  consensus/dccs/price_engine.go
  consensus/ethash/consensus.go
  contracts/nexty/contract/.gitignore
  contracts/nexty/endurio/package.json
  contracts/nexty/endurio/pairex/PairEx.go
  contracts/nexty/endurio/src/DataSet.sol
  contracts/nexty/endurio/src/Initializer.sol
  contracts/nexty/endurio/src/Migrations.sol
  contracts/nexty/endurio/src/OrderBook.sol
  contracts/nexty/endurio/src/PairEx.sol
  contracts/nexty/endurio/src/interfaces/IOwnableERC223.sol
  contracts/nexty/endurio/src/interfaces/IPairEx.sol
  contracts/nexty/endurio/src/tokens/ERC223.sol
  contracts/nexty/endurio/src/tokens/StableToken.sol
  contracts/nexty/endurio/src/tokens/VolatileToken.sol
  contracts/nexty/endurio/stable/StableToken.go
  contracts/nexty/endurio/volatile/VolatileToken.go
  contracts/nexty/governance/nexty.go
  contracts/nexty/governance/nexty.sol
  contracts/nexty/governance/package.json
  contracts/nexty/ntf/token.go
  contracts/nexty/ntf/token.sol
  core/chain_makers.go
  core/evm.go
  core/state_processor.go
  ethstats/ethstats.go
  miner/worker.go
  params/config.go
Labels: PR: unreviewed, nUSD, need:more-tests, priority:medium

#216 containers/docker: update dockerfile to build from nextyio/gonex
  containers/docker/develop-alpine/Dockerfile
  containers/docker/develop-ubuntu/Dockerfile
  containers/docker/master-alpine/Dockerfile
  containers/docker/master-ubuntu/Dockerfile
Labels: PR: unreviewed

#234 dccs: use state.IntermediateRoot in between state change
  consensus/dccs/dccs.go
  consensus/dccs/price_engine.go
Labels: PR: reviewed-approved

#236 dccs: return error when data/state is missing
  consensus/dccs/dccs.go
Labels: PR: reviewed-approved
