Repository nextyio/gonex, pull requests merged in 2019-02, with the labels that each got.

#134 trie/database: add a missing unlock
  trie/database.go
Labels: enhancement :up:

#135 p2p/protocols: some fixes on p2p protocol
  p2p/protocols/protocol.go
  p2p/protocols/reporter.go
Labels: bug :beetle:, priority:medium

#137 cmd: some minor fixes for bootnode
  cmd/bootnode/main.go
  cmd/utils/flags.go
Labels: PR: unreviewed

#126 Consensus address field name and address
  cmd/puppeth/wizard_genesis.go
  consensus/dccs/dccs.go
  eth/backend.go
  params/config.go
Labels: PR: reviewed-approved

#138 core/state: memory efficient, add AddPreimage test
  core/state/statedb.go
  core/state/statedb_test.go
Labels: PR: unreviewed, enhancement :up:

#109 Consensus level Contract Deployment
  cmd/puppeth/wizard_genesis.go
  consensus/dccs/dccs.go
  core/vm/evm.go
  params/config.go
Labels: PR: reviewed-approved

#139 travis,build: fix some failed testcases
  .travis.yml
  build/ci-notes.md
  build/ci.go
  build/dput-launchpad.cf
  cmd/geth/consolecmd_test.go
  consensus/clique/snapshot_test.go
  consensus/dccs/snapshot.go
  consensus/dccs/snapshot_test.go
  core/state/state_test.go
  core/state_transition.go
  core/tx_pool.go
  miner/worker.go
Labels: PR: unreviewed

#141 core, cmd/puppeth: implement constantinople fix, disable EIP-1283
  cmd/puppeth/genesis.go
  cmd/puppeth/module_dashboard.go
  cmd/puppeth/wizard_genesis.go
  core/vm/gas_table.go
  core/vm/logger_json.go
  params/config.go
  tests/init.go
  tests/rlp_test_util.go
  tests/state_test.go
Labels: PR: reviewed-approved, must:have, upstream

#142 dccs: dont get sealer list from cache at the ThangLong hardfork block
  consensus/dccs/dccs.go
Labels: PR: reviewed-approved, bug :beetle:, must:have, priority:low

#150 binding code for nexty governance and token smart contract
  cmd/puppeth/wizard_genesis.go
  common/deployer/contract.go
  consensus/dccs/dccs.go
  contracts/nexty/contract/nexty.go
  contracts/nexty/contract/nexty.sol
  contracts/nexty/nexty.go
  contracts/nexty/token/token.go
  contracts/nexty/token/token.sol
  params/config.go
Labels: PR: reviewed-approved, enhancement :up:

#151 trie: fix error in node decoding
  trie/encoding.go
  trie/trie_test.go
Labels: PR: unreviewed

#154 consensus/dccs: nil check the ThangLong config param on initialization
  consensus/dccs/dccs.go
Labels: PR: reviewed-approved

#155 add config and genesis for official nexty testnet
  cmd/utils/flags.go
  consensus/dccs/dccs.go
  core/genesis.go
  core/genesis_alloc.go
  params/config.go
  testnet.json
Labels: PR: unreviewed, feature :cake:, testnet

#156 Update Gorvernance Contract
  cmd/puppeth/wizard_genesis.go
  common/deployer/contract.go
  consensus/dccs/dccs.go
  contracts/nexty/contract/.gitignore
  contracts/nexty/contract/nexty.go
  contracts/nexty/contract/nexty.sol
  contracts/nexty/contract/package.json
  eth/backend.go
  params/config.go
Labels: PR: reviewed-approved

#158 rlp: added pooling of streams using sync
  rlp/decode.go
Labels: PR: unreviewed, upstream
